'use client';
import React from 'react';
import { motion } from 'framer-motion';
import { CheckCircle2, AlertTriangle, Globe, Lock, Shield, ShieldCheck, Eye, XCircle, AlertOctagon, Terminal, FileText, Download } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ScanResponse {
    url: string;
    is_phishing: boolean;
    confidence_score: number;
    risk_level: string;
    domain_age_days?: number;
    status: string;
    insights?: string[];
}

const ResultCard = ({ result }: { result: ScanResponse }) => {
    const isSafe = result.risk_level === 'SAFE' || result.risk_level === 'Low';
    const isCaution = result.risk_level === 'CAUTION' || result.risk_level === 'Medium' || result.risk_level === 'High';
    const isCritical = result.risk_level === 'CRITICAL' || result.is_phishing;
    const isVerified = result.status === 'VERIFIED';
    const safeUrl = result?.url || '';

    // PDF Generation Logic
    const handleDownloadPDF = () => {
        if (!result) {
            alert("No scan data available");
            return;
        }

        const doc = new jsPDF();

        // 1. Header
        doc.setFontSize(20);
        doc.setFont("helvetica", "bold");
        doc.text("PhishGuard Security Report", 10, 20);

        // Line Separator
        doc.setLineWidth(0.5);
        doc.line(10, 25, 200, 25);

        // 2. Scan Details
        doc.setFontSize(12);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(0, 0, 0);

        doc.text(`Target URL: ${safeUrl}`, 10, 40);
        doc.text(`Scan Date: ${new Date().toLocaleString()}`, 10, 50);

        // Risk Level with Color Coding
        doc.text("Risk Level: ", 10, 60);
        if (isSafe) {
            doc.setTextColor(0, 128, 0); // Green
        } else if (isCaution) {
            doc.setTextColor(255, 165, 0); // Orange
        } else {
            doc.setTextColor(255, 0, 0); // Red
        }
        doc.text(result.risk_level, 35, 60);

        // Reset Text Color
        doc.setTextColor(0, 0, 0);

        // 3. Insights Table
        if (result.insights && result.insights.length > 0) {
            // Map insights to array of arrays for autoTable
            const tableBody = result.insights.map((insight) => [insight]);

            autoTable(doc, {
                startY: 70,
                head: [['Security Insights / Reasons']],
                body: tableBody,
                theme: 'grid',
                headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold' },
                styles: { fontSize: 10, cellPadding: 3 },
                alternateRowStyles: { fillColor: [245, 245, 245] }
            });
        }

        // 4. Footer
        const pageHeight = doc.internal.pageSize.height;
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text("Generated by PhishGuard AI", 10, pageHeight - 10);

        // 5. Save
        doc.save('PhishGuard_Report.pdf');
    };

    let statusColor = 'text-red-600';
    let bgStatus = 'bg-red-50';
    let borderStatus = 'border-red-200';
    let icon = <AlertTriangle className="w-12 h-12 text-red-600" />;

    if (isSafe) {
        statusColor = 'text-emerald-600';
        bgStatus = 'bg-emerald-50';
        borderStatus = 'border-emerald-200';
        icon = <ShieldCheck className="w-12 h-12 text-emerald-600" />;
    } else if (isCaution) {
        statusColor = 'text-amber-600';
        bgStatus = 'bg-amber-50';
        borderStatus = 'border-amber-200';
        icon = <Eye className="w-12 h-12 text-amber-600" />;
    }

    const container = {
        hidden: { opacity: 0 },
        show: {
            opacity: 1,
            transition: {
                staggerChildren: 0.1
            }
        }
    };

    const item = {
        hidden: { opacity: 0, y: 20 },
        show: { opacity: 1, y: 0 }
    };

    return (
        <motion.div
            variants={container}
            initial="hidden"
            animate="show"
            className="w-full mt-6 space-y-4"
        >
            {/* Status Banner */}
            <motion.div
                className={`flex flex-col items-center justify-center p-6 rounded-lg border ${borderStatus} ${bgStatus} text-center shadow-lg backdrop-blur-sm`}
                initial={{ scale: 0.95, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                transition={{ duration: 0.4 }}
                variants={item}
            >
                <div className="mb-3 bg-white/90 p-3 rounded-full shadow-sm ring-1 ring-black/5">
                    {icon}
                </div>
                <h2 className={`text-2xl font-bold tracking-tight ${statusColor} flex items-center gap-2 uppercase`}>
                    {isSafe ? 'Verified Safe' : isCaution ? 'Caution: Unverified Project' : 'Critical Threat Detected'}
                    {isVerified && (
                        <span className="px-2 py-0.5 bg-emerald-100 text-emerald-700 text-xs font-bold uppercase rounded-full border border-emerald-200 tracking-wide">
                            Verified Entity
                        </span>
                    )}
                </h2>
                <p className="text-gray-500 text-sm mt-1">
                    {isSafe
                        ? 'No phishing indicators found on this URL.'
                        : isCaution
                            ? 'PROCEED WITH CAUTION: This project is unverified.'
                            : 'This URL has been flagged as malicious.'}
                </p>
            </motion.div>

            {/* Metrics Grid */}
            <motion.div variants={item} className="grid grid-cols-2 gap-4">
                <div className="p-4 rounded-lg border border-gray-200 bg-gray-50 flex flex-col items-center justify-center">
                    <span className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Confidence</span>
                    <span className={`text-2xl font-bold ${statusColor}`}>{result.confidence_score}%</span>
                </div>
                <div className="p-4 rounded-lg border border-gray-200 bg-gray-50 flex flex-col items-center justify-center">
                    <span className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Risk Level</span>
                    <div className={`px-2 py-1 rounded text-xs font-bold ${isSafe ? 'bg-emerald-100 text-emerald-700' : isCaution ? 'bg-amber-100 text-amber-700' : 'bg-red-100 text-red-700'}`}>
                        {result.risk_level.toUpperCase()}
                    </div>
                </div>
            </motion.div>

            {/* Technical Details */}
            <motion.div variants={item} className="rounded-lg border border-gray-200 divide-y divide-gray-100 text-sm">
                <div className="flex justify-between items-center p-3">
                    <span className="text-gray-500 flex items-center gap-2"><Globe className="w-4 h-4" /> Host</span>
                    <span className="font-medium text-gray-900 truncate max-w-[200px]">
                        {safeUrl.replace(/^https?:\/\//, '').split('/')[0]}
                    </span>
                </div>
                <div className="flex justify-between items-center p-3">
                    <span className="text-gray-500 flex items-center gap-2"><Lock className="w-4 h-4" /> Protocol</span>
                    <span className="font-medium text-gray-900">
                        {safeUrl.startsWith('https') ? 'HTTPS (Secure)' : 'HTTP (Unsecure)'}
                    </span>
                </div>
                <div className="flex justify-between items-center p-3">
                    <span className="text-gray-500 flex items-center gap-2"><CheckCircle2 className="w-4 h-4" /> Domain Age</span>
                    <span className="font-medium text-gray-900">
                        {result.domain_age_days ? `${Math.floor(result.domain_age_days / 365)} Years` : 'Unknown'}
                    </span>
                </div>
                {!isSafe && (
                    <div className="flex justify-between items-center p-3 bg-red-50/50">
                        <span className="text-red-600 font-medium flex items-center gap-2"><Shield className="w-4 h-4" /> Action</span>
                        <span className="font-bold text-red-700">DO NOT VISIT</span>
                    </div>
                )}
                <button
                    onClick={handleDownloadPDF}
                    className="w-full mt-3 py-2 flex items-center justify-center gap-2 bg-gray-900 hover:bg-black text-white rounded-md text-sm font-medium transition-colors"
                >
                    <Download className="w-4 h-4" /> Download Security Report
                </button>
            </motion.div>

            {/* Security Analysis / Insights Section */}
            {result.insights && result.insights.length > 0 && (
                <motion.div variants={item} className="mt-6">
                    <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3 flex items-center gap-2">
                        <Terminal className="w-4 h-4" /> Security Analysis
                    </h3>
                    <div className="bg-white/50 backdrop-blur-sm rounded-lg border border-gray-200 overflow-hidden">
                        {result.insights.map((insight, index) => {
                            // Emoji-based styling logic
                            let icon = <CheckCircle2 className="w-4 h-4 text-emerald-500" />;
                            let textColor = "text-gray-600";
                            let bgColor = "bg-transparent";

                            if (insight.startsWith('🚨') || insight.startsWith('💣') || insight.startsWith('🎣')) {
                                icon = <AlertOctagon className="w-4 h-4 text-red-500" />;
                                textColor = "text-red-700";
                                bgColor = "bg-red-50/50";
                            } else if (insight.startsWith('⚠️') || insight.startsWith('🔓')) {
                                icon = <AlertTriangle className="w-4 h-4 text-amber-500" />;
                                textColor = "text-amber-700";
                                bgColor = "bg-amber-50/50";
                            }

                            // Strip emoji for clean text display
                            const cleanText = insight.substring(2).trim();

                            return (
                                <motion.div
                                    key={index}
                                    initial={{ opacity: 0, x: -10 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    transition={{ delay: index * 0.1 }}
                                    className={`flex items-start gap-3 p-3 border-b border-gray-100 last:border-0 ${bgColor}`}
                                >
                                    <div className="mt-0.5 shrink-0">{icon}</div>
                                    <span className={`text-sm font-medium ${textColor}`}>{cleanText}</span>
                                </motion.div>
                            );
                        })}
                    </div>
                </motion.div>
            )}
        </motion.div>
    );
};

export default ResultCard;
